name: lab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/images/image.png

  # Uncomment and add additional assets if needed
  # assets:
  #   - images/railway.png
